//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compañia
    {
        public Compañia()
        {
            this.Item = new HashSet<Item>();
            this.Sucursal = new HashSet<Sucursal>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> RowIDERP { get; set; }
        public Nullable<int> EmpresaID { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Item> Item { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
    }
}
