//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opcion
    {
        public Opcion()
        {
            this.Actividad = new HashSet<Actividad>();
            this.Actividad1 = new HashSet<Actividad>();
            this.Actividad2 = new HashSet<Actividad>();
            this.Actividad3 = new HashSet<Actividad>();
            this.Empresa = new HashSet<Empresa>();
            this.Empresa1 = new HashSet<Empresa>();
            this.Sucursal = new HashSet<Sucursal>();
            this.Sucursal1 = new HashSet<Sucursal>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> AgrupacionID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ICollection<Actividad> Actividad { get; set; }
        public virtual ICollection<Actividad> Actividad1 { get; set; }
        public virtual ICollection<Actividad> Actividad2 { get; set; }
        public virtual ICollection<Actividad> Actividad3 { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<Empresa> Empresa1 { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
        public virtual ICollection<Sucursal> Sucursal1 { get; set; }
        public virtual Agrupacion Agrupacion { get; set; }
    }
}
