//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public Sucursal()
        {
            this.PuntoEnvio = new HashSet<PuntoEnvio>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> RowIDERP { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CompañiaID { get; set; }
        public Nullable<int> TerceroID { get; set; }
        public Nullable<int> VendedorID { get; set; }
        public Nullable<int> ContactoERPID { get; set; }
        public Nullable<int> ListaPrecioID { get; set; }
        public Nullable<int> TipoSucursalID { get; set; }
        public Nullable<int> CondicionPago { get; set; }
        public string CentroOperacion { get; set; }
        public Nullable<bool> BloqueoCupo { get; set; }
        public Nullable<bool> BloqueoMora { get; set; }
        public Nullable<double> CupoCredito { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual Compañia Compañia { get; set; }
        public virtual ContactoERP ContactoERP { get; set; }
        public virtual ListaPrecio ListaPrecio { get; set; }
        public virtual ICollection<PuntoEnvio> PuntoEnvio { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Tercero Tercero { get; set; }
        public virtual Opcion Opcion1 { get; set; }
        public virtual Tercero Tercero1 { get; set; }
    }
}
